arch:
  - arm64
os:
  - linux
services:
  - docker
before_install:
  - cd 8.0/debian-10/ && docker build -t toyangdon/bitnami-mysql:latest -f Dockerfile .
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
script:
  - docker push toyangdon/bitnami-mysql:latest
